export const SITE = {
  website: "https://jacobsidian.com/",
  author: "Jacob",
  profile: "",
  desc: "jacobsidian — 글, 책 노트, 개발 기록",
  title: "jacobsidian",
  ogImage: "",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 5,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ko",
  timezone: "Asia/Seoul",
} as const;
